<a href="https://colab.research.google.com/github/CharlieWalkerHimanshu/TensorFlow/blob/Charlie/Introduction_to_TensorFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Tensors**
A tensor is  a generalization of vectors and metrics to potentially higher dimensions. Internally, TensorFlow represents tensors as n-dimesnional arrays of datatypes. (https://www.tensorflow.org/guide)

It shouldn't be suprise you that tensors are a fundamental aspect of TensorFlow. They are the main objects that are passed around and manipulated throughout a program. Each tensors represents a partially defined computation that will eventually produce a value. TesnorFlow programs work by building a graph of Tensor objects that details how tensors are related. Running different parts of the graph allow results to generated.

Each Tensor has a datatype and a shape.

**Data Type include:** float32, int32, string and others.

**Shape:** Represents the dimension of data.

## Creating Tensors

Below is an example of how to create some different tensors

In [2]:
import tensorflow as tf

string = tf.Variable("this is a string", tf.string)
number = tf.Variable(324, tf.int16)
floating = tf.Variable(3.567, tf.float64)

### Rank/Degree if Tensors

Another word for a rank is, these terms simply mean the number of dimensions involved in the tensor. What we created above is a tensor of rank 0, also known as a scalar.

Now we'll create some tensors of higher degrees/ranks.

In [3]:
rank1_tensor = tf.Variable(["test"], tf.string)
rank2_tensor = tf.Variable([["Test", "ok"], ["test", "yes"]], tf.string)

To determine the rank of a tensor we call the following method

In [4]:
tf.rank(rank2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

### Shape of Tensors

Now that we've talked about the rank of tensors it's time to talk about the shape. The shape of a tensor is simply the amount of elementsthat exist in each dimension. TensorFlow will try to determine the shape of a tensor ut sometimes it may be unknown.

To get the shape of a tensor we use the shape attribute.

In [5]:
rank2_tensor.shape

TensorShape([2, 2])

### Changing Shape

The number of elements of a tensor is the product of the sizes of all it's shapes. there are oftern many shapes that have the same number of elements, making it convenient to be able to change the shape of a tensor

The example below shows how to change the shape of a tensor.

In [6]:
tensor1 = tf.ones([1,2,3]) # tf.ones() creates a shape [1,2,3] tensor full of ones
tensor2 = tf.reshape(tensor1, [2,3,1]) # reshape existing data to shape [2,3,1]
tensor3 = tf.reshape(tensor2, [3, -1]) #-1 tells the tensor to calculate the size of the dimension in that place
                                      # this will reshape the tensor to [3,3]

# The numer of elements in the reshaped tensor MUST match the number in the original

Now let's have a look at our different tensors.

In [7]:
print(tensor1)
print(tensor2)
print(tensor3)
#notice the changes the shape

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


### **Slicing Tensors**
You may be familiar with the term "slice" in python and its use on lists, tuples etc. Well the slice operator can be used on tensors to select specific axes or elements.

When we slice or select elements from a tensor, we can use comma seperated values inside the set of square brackets. Each subsequent value refrences a different dimension of the tensor.

Ex: tensor[dim1, dim2, dim3]

I've included a few examples that will hopefully help illustrate how we can manipulate tensors with the slice operator.

In [8]:
#creating a 2d tensor
matrix = [[1,2,3,4,5],
          [6,7,8,9,10],
          [11,12,13,14,15],
          [16,17,18,19,20]]

tensor = tf.Variable(matrix, dtype=tf.int32)
print(tf.rank(tensor))
print(tensor.shape)

tf.Tensor(2, shape=(), dtype=int32)
(4, 5)


In [9]:
#now lets select some different rows and columns from our tensor

three = tensor[0,2] # selects the 3rd element from 1st row
print(three) # -> 3

row1 = tensor[0] # selects the first row
print(row1)

column1 = tensor[:, 0] # selects the first column
print(column1)

row_2_and_4 = tensor[1::2] # selects second and fourth row
print(row_2_and_4)

column_1_in_row_2_and_3 = tensor[1:3, 0]
print(column_1_in_row_2_and_3)

tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)
tf.Tensor([ 1  6 11 16], shape=(4,), dtype=int32)
tf.Tensor(
[[ 6  7  8  9 10]
 [16 17 18 19 20]], shape=(2, 5), dtype=int32)
tf.Tensor([ 6 11], shape=(2,), dtype=int32)


### **Types of Tensors**
Before we go to far, I will mention that there are diffent types of tensors. These are the most used and we will talk more in depth about each as they are used.

*   Variable
*   Constant
*   Placeholder
*   SparseTensor

With the execption of Variable all these tensors are immuttable, meaning their value may not change during execution.

For now, it is enough to understand that we use the Variable tensor when we want to potentially change the value of our tensor.

### **Sources**
Most of the information is taken direclty from the TensorFlow website which can be found below.

https://www.tensorflow.org/guide/tensor